//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWW_EF_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Labs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Labs()
        {
            this.LabEvents = new HashSet<LabEvents>();
        }
    
        public int Id { get; set; }
        public string Room { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Name { get; set; }
        public byte BlockNumber { get; set; }
        public int DayOfWeek { get; set; }
        public int Course_Id { get; set; }
    
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabEvents> LabEvents { get; set; }
        public virtual Labs_LabWithGroups Labs_LabWithGroups { get; set; }
        public virtual Labs_LabWithoutGroups Labs_LabWithoutGroups { get; set; }
    }
}
