//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWW_EF_DBFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabminEntities : DbContext
    {
        public LabminEntities()
            : base("name=LabminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnwesenheitSet> AnwesenheitSet { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<ExerciseResults> ExerciseResults { get; set; }
        public virtual DbSet<ExerciseTemplates> ExerciseTemplates { get; set; }
        public virtual DbSet<LabEvents> LabEvents { get; set; }
        public virtual DbSet<LabGroups> LabGroups { get; set; }
        public virtual DbSet<Labs> Labs { get; set; }
        public virtual DbSet<Labs_LabWithGroups> Labs_LabWithGroups { get; set; }
        public virtual DbSet<Labs_LabWithoutGroups> Labs_LabWithoutGroups { get; set; }
        public virtual DbSet<Testats> Testats { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
