//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWW_EF_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testats
    {
        public int CourseId { get; set; }
        public int StudentId { get; set; }
        public int LabEventId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public bool Success { get; set; }
        public int Auditor_Id { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual LabEvents LabEvents { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
