//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWW_EF_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monitor()
        {
            this.Preis = new Waehrung();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int HerstellerId { get; set; }
    
        public Waehrung Preis { get; set; }
    
        public virtual Hersteller Hersteller { get; set; }
    }
}
