// <auto-generated />
namespace VWW_EF_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class monitor_hersteller_assoc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(monitor_hersteller_assoc));
        
        string IMigrationMetadata.Id
        {
            get { return "201605121307244_monitor_hersteller_assoc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
