//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWW_V4_WCF2Client.myWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/VWW_V4_WCF")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myWebService.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/IsAdult", ReplyAction="http://tempuri.org/IMyService/IsAdultResponse")]
        bool IsAdult(VWW_V4_WCF2Client.myWebService.User usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/IsAdult", ReplyAction="http://tempuri.org/IMyService/IsAdultResponse")]
        System.Threading.Tasks.Task<bool> IsAdultAsync(VWW_V4_WCF2Client.myWebService.User usr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/getUser", ReplyAction="http://tempuri.org/IMyService/getUserResponse")]
        VWW_V4_WCF2Client.myWebService.User getUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/getUser", ReplyAction="http://tempuri.org/IMyService/getUserResponse")]
        System.Threading.Tasks.Task<VWW_V4_WCF2Client.myWebService.User> getUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/print", ReplyAction="http://tempuri.org/IMyService/printResponse")]
        void print(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/print", ReplyAction="http://tempuri.org/IMyService/printResponse")]
        System.Threading.Tasks.Task printAsync(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : VWW_V4_WCF2Client.myWebService.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<VWW_V4_WCF2Client.myWebService.IMyService>, VWW_V4_WCF2Client.myWebService.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAdult(VWW_V4_WCF2Client.myWebService.User usr) {
            return base.Channel.IsAdult(usr);
        }
        
        public System.Threading.Tasks.Task<bool> IsAdultAsync(VWW_V4_WCF2Client.myWebService.User usr) {
            return base.Channel.IsAdultAsync(usr);
        }
        
        public VWW_V4_WCF2Client.myWebService.User getUser() {
            return base.Channel.getUser();
        }
        
        public System.Threading.Tasks.Task<VWW_V4_WCF2Client.myWebService.User> getUserAsync() {
            return base.Channel.getUserAsync();
        }
        
        public void print(string text) {
            base.Channel.print(text);
        }
        
        public System.Threading.Tasks.Task printAsync(string text) {
            return base.Channel.printAsync(text);
        }
    }
}
